filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: https://hazem-internship.github.io/gow-new-1/
templates: {}
renderedvalues: {}
